// Writes a .env for an offline demo: a freshly generated Ed25519 key pair (so scripts/simulate.ts
// can sign requests like Discord does), a random encryption key, and Discord/AI APIs pointed at
// scripts/mock-discord.ts. Refuses to overwrite an existing .env.
import { existsSync, writeFileSync } from "node:fs";
import nacl from "tweetnacl";
import { bytesToBase64 } from "../src/worker/lib/crypto";
import { flag, hex } from "./_shared";

if (existsSync(".env") && !flag("force")) {
  console.error(".env already exists (use --force to replace it with demo values).");
  process.exit(1);
}

const seed = crypto.getRandomValues(new Uint8Array(32));
const keyPair = nacl.sign.keyPair.fromSeed(seed);

writeFileSync(
  ".env",
  `# Offline demo values generated by scripts/dev-setup.ts — not real credentials.
DISCORD_APPLICATION_ID=100000000000000001
DISCORD_PUBLIC_KEY=${hex(keyPair.publicKey)}
DISCORD_BOT_TOKEN=demo-bot-token
DISCORD_CLIENT_SECRET=demo-client-secret
ENCRYPTION_KEY=${bytesToBase64(crypto.getRandomValues(new Uint8Array(32)))}
AI_API_KEY=demo-ai-key
DISCORD_API_BASE=http://localhost:8790/api/v10
AI_BASE_URL=http://localhost:8790/ai/v1
AI_MODEL=demo-model
# Private half of the demo key, used only by scripts/simulate.ts to sign fake interactions.
DEV_SIGNING_SEED=${hex(seed)}
`,
);
console.log("Wrote .env with demo values. Next: npm run db:migrate:local && npm run demo:admin");
